server:
  port: 8080
  
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

springdoc.swagger-ui:
  path: /swagger-ui.html
  config-url: /v3/api-docs/swagger-config#/t-converter-controller/convert